name: Chrysus
version: 1.0
description: >
  Creates a a complex dynamic economy
author: Tritania
website: https://github.com/tritania/Chrysus

main: org.tritania.chrysus.Chrysus

commands:
  csell:
    description: Sells items that a player owns
    aliases: []
    usage: /<command> [item] [amount] [price] [time]
  cbuy:
    description: Buy items in the market
    aliases: []
    usage: /<command> [item][amount] [price] [time] | [orderid]
  cclean:
    description: Cleans a specified players economic data
    aliases:
    usage:
  cdesc:
    description: Gives economic data 
    aliases: []
    usage: /<command> [item] | [company] | [playername]
  cinc:
    description: Player run company control
    aliases: []
    usage: /<command> 
  cisk:
    description: Gives general chrysus information
    aliases: []
    usage: /<command> [help]
    
